# Generated by Django 4.2.17 on 2025-01-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_productchanges_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchanges',
            name='product',
            field=models.IntegerField(),
        ),
    ]
