# Generated by Django 4.2.17 on 2025-01-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_productchanges_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productchanges',
            old_name='product',
            new_name='product_id',
        ),
    ]
